import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>AVG Wireframes!</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='backdrop-blue-sm container mt-8 flex w-screen flex-col justify-center rounded-lg bg-white/20 p-12 text-3xl text-white'>
          <section id='main' className='mb-8'>
            <h1>Hey there!</h1>
            <p>
              It&#39;s good to see you here! This project is a small sample of
              some wireframes I was doing, and hopefully some of it caught your
              eye.
            </p>
          </section>
          <section className='mb-8'>
            <p>
              <span>I think that I managed to hit some expected KPIs</span>
              <div>
                &nbsp;&nbsp;&#x2022; Got a full tailwindCSS framework up and
                running
              </div>
              <div>
                &nbsp;&nbsp;&#x2022; Identified (hopefully correctly) that this
                question involves a modal. Otherwise I think I may have jumped
                through a few hoops too many
              </div>
              <div>
                &nbsp;&nbsp;&#x2022; Got more or less the priciples of what the
                question had asked CSS-wise, even though not all of the styles
                are in
              </div>
            </p>
          </section>
          <section className='mb-8'>
            <p>
              <span>Some KPIs I definitely missed</span>
              <div>
                &nbsp;&nbsp;&#x2022; No button styling, and some missing border
                styling. I do not think that that is such a big deal, but the
                button component should have had been externalized. It could
                have been used elsewhere.
              </div>
              <div>
                &nbsp;&nbsp;&#x2022; For those components that were styled,
                perhaps some different choices were in order (though I know I
                have terrible taste. Case-and-point: brown lettering in the
                header bar)
              </div>
            </p>
          </section>
          <section className='mb-8'>
            <p>
              In the immortal words of some hallmark card writer somewhere
              hoping to get quoted someday:
              <pre className='italic'>
                I hope that you find what you&#39;re looking for
              </pre>
              <pre className='text-xs'>
                ** Gimme a call if you do, I really need this job
              </pre>
            </p>
          </section>
        </div>
      </main>
    </>
  )
}
